[package]
name = "kafka-test"
version = "0.1.0"
authors = ["vinz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = { version = "0.22", features = ["cmake-build"] }